### PR TITLE
CMake: Add Initial support for K64F and SX1276 shield

### PR DESCRIPTION
**Pull request by hugueskamba**
Also remove the `mbed-lora-radio-drv` library as the shield drivers are
in Mbed OS 6 under the `components` directory.

### CODE REVIEW

**Comment by 0xc0170** [comment]
@hugueskamba The CI fails, can you verify? I'll merge this but we shall keep it green

**Comment by hugueskamba** [comment]
I have pushed a commit that changes the Mbed OS SHA used but it is not being shown in Github. There seem to be an [issue with GitHub](https://www.githubstatus.com/incidents/d60fmldlvw48).

**Comment by 0xc0170** [comment]
> I have pushed a commit that changes the Mbed OS SHA used but it is not being shown in Github. There seem to be an issue with GitHub.

Github is back, new push?

**Comment by hugueskamba** [comment]
> > I have pushed a commit that changes the Mbed OS SHA used but it is not being shown in Github. There seem to be an issue with GitHub.
> 
> Github is back, new push?

 I have already tried it. I might have to close this PR and open a new one.

**Pull request merged**
