### PR TITLE
Pins configured at driver level

### PR DESCRIPTION
**Pull request by jeromecoutant**
Hi

This development is following https://github.com/ARMmbed/mbed-os/pull/14049

Pins are now defined at driver level.
Application just need to override the needed pins.

Note that as DISCO_L072CZ_LRWAN1 is LORA capable by default, specific configuration is removed.

@ludoch-stm

### CODE REVIEW

**Comment by jeromecoutant** [comment]
Hi
https://github.com/ARMmbed/mbed-os/pull/14049 is about to be merged.
Please review this one

**Review by paul-szczepanek-arm — CHANGES_REQUESTED** [review]
So the change is that the config is now done per module - looks good to me.

Please target development branch.

**Comment by paul-szczepanek-arm** [comment]
Does this supersede https://github.com/ARMmbed/mbed-os-example-lorawan/pull/181 ?

**Comment by paul-szczepanek-arm** [comment]
I switched the branch for you - on all examples development is the branch used by mbed-os, master is only used by our bots for making releases.

**Review by paul-szczepanek-arm — APPROVED** [review]

**Comment by paul-szczepanek-arm** [comment]
Needs ARMmbed/mbed-os#14049 to land first

**Pull request merged**
