### PR TITLE
Merge old configs into main config

### PR DESCRIPTION
**Pull request by paul-szczepanek-arm**
This remove the old configs which are no longer valid. I merged the missing configs into the main config. This is done through a custom target so you can have both defined.

The SX126X had an issue with option names which I fixed.

### CODE REVIEW

**Comment by paul-szczepanek-arm** [comment]
@jeromecoutant can you please take a look?

**Comment by paul-szczepanek-arm** [comment]
note to self: close https://github.com/ARMmbed/mbed-os-example-lorawan/issues/216 on merge

**Comment by jeromecoutant** [comment]
> note to self: close #216 on merge

You should add "fix #216" in the PR description, and GitHub will close the issue automatically :-)

**Review by jeromecoutant — APPROVED** [review]

**Comment by paul-szczepanek-arm** [comment]
Didn't know about that one, thanks, I'll try it next time

**Pull request merged**
