### PR TITLE
Create lora objects into heap

### PR DESCRIPTION
**Pull request by kivaisan**
In order to reduce stack usage, create lora objects into heap.

### CODE REVIEW

**Comment by AnttiKauppila** [comment]
Wait for 5.8.3 to be released, merge only after that

**Comment by janjongboom** [comment]
Why do we need to create them on the heap now? That's just moving the problem?

**Comment by hasnainvirk** [comment]
@kivaisan @AnttiKauppila It's actually easier to handle memory outage if the stuff is on stack. It has been the norm lately in Mbed world to use stack for storage.

**Comment by kivaisan** [comment]
Ok. Good point. I'll close this PR.

**Pull request closed without merging**
