### PR TITLE
Updating docs

### PR DESCRIPTION
**Pull request by hasnainvirk**
Documentation update

### CODE REVIEW

**Comment by hasnainvirk** [comment]
@peknis01 Could you please review this ?

**Comment by peknis01** [comment]
@AnotherButler, it's a bit hectic with Cloud. Any chance?

**Comment by AnotherButler** [comment]
@hasnainvirk Could you please give me permissions to fork and edit?

**Comment by AnttiKauppila** [comment]
The content looks fine, but leave this for the Docs team to check spelling on this.

**Comment by hasnainvirk** [comment]
@AnotherButler I added you as a collaborator. You should be able to add edit commits on top of this commit.

**Comment by AnotherButler** [comment]
@hasnainvirk Thanks for the permissions. Nice work on this 👍 I hope you don't mind, but I also copy edited some of the existing content to fix some typos I spotted.

**Comment by janjongboom** [comment]
@hasnainvirk you also need newlib-nano for the 6K target. Maybe put link to https://os.mbed.com/blog/entry/Reducing-memory-usage-with-a-custom-prin/ too.

**Pull request merged**
